# Generated by Django 4.2.20 on 2025-09-24 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_topic_voiceresponse_topicattempt_learningsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-due_date', 'title']},
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assignment',
            name='assignment_type',
            field=models.CharField(choices=[('standard', 'Standard Assignment'), ('voice', 'Voice-Activated Assignment'), ('interactive', 'Interactive Quiz')], default='standard', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='estimated_duration',
            field=models.IntegerField(default=30, help_text='Estimated duration in minutes'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='expected_responses',
            field=models.JSONField(blank=True, help_text='Expected voice responses', null=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='assignment',
            name='target_grade_levels',
            field=models.CharField(blank=True, help_text='Comma-separated grade levels', max_length=100),
        ),
        migrations.AddField(
            model_name='assignment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='assignment',
            name='voice_prompt',
            field=models.TextField(blank=True, help_text='Voice prompt for voice-activated assignments'),
        ),
        migrations.CreateModel(
            name='AssignmentStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('time_spent', models.IntegerField(default=0, help_text='Time spent in minutes')),
                ('voice_responses_count', models.IntegerField(default=0)),
                ('last_voice_interaction', models.DateTimeField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
