# Generated by Django 5.2.6 on 2025-09-24 21:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_achievement_student_can_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blockchain_id',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='blockchain_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='last_blockchain_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='profile_hash',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='progress_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('progress', 'Progress Update'), ('profile', 'Profile Change'), ('achievement', 'Achievement Earned'), ('assignment', 'Assignment Completion'), ('voice', 'Voice Interaction')], max_length=20)),
                ('transaction_hash', models.CharField(max_length=66, unique=True)),
                ('block_number', models.IntegerField()),
                ('data_hash', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('gas_used', models.IntegerField(blank=True, null=True)),
                ('contract_used', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.student')),
            ],
        ),
        migrations.AddField(
            model_name='studentachievement',
            name='blockchain_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blockchainrecord'),
        ),
        migrations.AddField(
            model_name='studentprogress',
            name='blockchain_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blockchainrecord'),
        ),
        migrations.AddField(
            model_name='voiceinteraction',
            name='blockchain_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.blockchainrecord'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['student', 'transaction_type'], name='base_blockc_student_b26b68_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['transaction_hash'], name='base_blockc_transac_c3b6ce_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['block_number'], name='base_blockc_block_n_e11b42_idx'),
        ),
        migrations.AddIndex(
            model_name='blockchainrecord',
            index=models.Index(fields=['timestamp'], name='base_blockc_timesta_4281d1_idx'),
        ),
    ]
